version: "3"
services:
  web:
    environment:
        - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - "3000:3000"
    volumes:
      - /home/dtairych/app/node_modules
      - .:/home/dtairych/app
  tests:
    environment:
        - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - /home/dtairych/app/node_modules
      - .:/home/dtairych/app
    command: ["npm", "run", "test"]